### ISSUE TITLE
Whip mica-vmm-occurrences

### ISSUE THREAD

**Issue by peterdesmet** [inbo/mica-occurrences#10]
- [x] occurrenceID: duplicates
- [x] samplingProtocol: write as `rat trap`
- [x] eventDate: full dates with day possible?
- [x] recordedBy: would write as `VMM team BENEDENSCHELDE` rather than `VMM:team:BENEDENSCHELDE`
- [x] locationRemark: correct value to `CAT3 - not navigable cat. 3`
- [x] stateProvince: use English names, see https://en.wikipedia.org/wiki/Provinces_of_Belgium
- [x] stateProvince / municipality: leave `Onbekend` empty
- [ ] decimalLatitude: three values below 50.67
- [ ] decimalLongitude: two values below 2.53
- [x] geodeticDatum: field is listed twice, keep the second one
- [x] identifiedBy: RATO: drop this field, probably incorrect?
- [x] vernacularName: technically, this should appear after taxonRank
- [x] vernacularName: `Tachybaptus ruficollis` should be `Dodaars`
- [x] taxonRank: `Zapornia pusilla intermedia (Hermann, 1804)` should have `subspecies`

**Comment by DimEvil** [comment]
Zapornia pusilla intermedia (Hermann, 1804) --> wrong taxonomic interpretation by GBIF based on the vernacularName. I'll change in this one:  Gallinula chloropus (Linnaeus, 1758).

**Comment by DimEvil** [comment]
this one can be whipped again. Duplicate occurrences are split
Did not fix decimalLat and long

**Comment by peterdesmet** [comment]
Looks good, except for the `decimalLat/Long` as mentioned and:

- [x] occurrenceID2: remove column
- [x] occurrenceID: please use colon for duplicates: `MICA:VMM:OCC:334023:1` not `MICA:VMM:OCC:334023_1`

**Comment by DimEvil** [comment]
@peterdesmet  shoudl be ok now
