### ISSUE TITLE
Have better datasetName for Agouti occurrences

### ISSUE THREAD

**Issue by peterdesmet** [inbo/mica-occurrences#14]
@EmmaCartuyvels1 the current title for this dataset is:

> MICA - Muskrat and Coypu camera trap occurrences collected in Belgium, the Netherlands and Germany

But the dataset obviously contains much more. Is there a better name we could give to this dataset? The structure of the title should be something like:

> MICA - ... in location

**Comment by EmmaCartuyvels1** [comment]
MICA- Camera trap occurrences in Belgium, the Netherlands and Germany?

**Comment by DimEvil** [comment]
If these traps have a focus on Coypu and Muskrat, I would keep the tittle. All the others (ok, it's a lot) are 'by-catch' .

**Comment by jimcasaer** [comment]
@EmmaCartuyvels1 should there be a reference to Life in the title of the dataset ?
reference to Life projectnumber ?

**Comment by peterdesmet** [comment]
@jimcasaer this will be in the dataset metadata. Ok to leave long dataset title, will just use "observations" rather than "occurrences collected":

> MICA - Muskrat and Coypu camera trap observations in Belgium, the Netherlands and Germany
