### ISSUE TITLE
What license to choose for the images

### ISSUE THREAD

**Issue by peterdesmet** [inbo/mica-occurrences#16]
The license for the data will be CC0 as usual, but what license to we want to use for the images? Also CC0 or rather CC-BY?

@EmmaCartuyvels1 @jimcasaer let me know if you need more guidance for this decision

**Comment by EmmaCartuyvels1** [comment]
I would say CC-BY based on my limited knwoledge of licenses

**Comment by peterdesmet** [comment]
Ok, that is how it is defined now:

https://github.com/inbo/mica-occurrences/blob/3d0276779fc67d5fc6b76b1435b39cce1e149201/datasets/mica-agouti-occurrences/specs/dwc_multimedia.yaml#L20-L21
