### ISSUE TITLE
Use same project info for all MICA datasets

### ISSUE THREAD

**Issue by peterdesmet** [inbo/mica-occurrences#17]
- [x] Create default MICA project description
- [x] Update http://ipt.nlbif.nl/resource?r=mica-uvw-occurrences#project
- [x] Update https://ipt.inbo.be/resource?r=mica-rato-occurrences#project
- [x] Update https://ipt.inbo.be/resource?r=mica-legacy-occurrences#project
- [x] Update https://ipt.inbo.be/resource?r=mica-agouti-occurrences#project

## Title
MICA - Management of Invasive Coypu and muskrAt in Europe
## Identifier
LIFE18 NAT/NL/001047
## Description
Invasive alien species such as the coypu and muskrat pose a major threat to biodiversity and cost millions of euros annually. By feeding on rushes and reeds, these animals cause serious damage to the environment in which they live and endangered species suffer from habitat loss. The disappearance of reeds and digging in dikes represents a safety risk for humans in the lowland areas. With the LIFE project MICA (https://lifemica.eu/), the partners from the participating countries want to develop a transnational plan for the management of coypu and muskrat populations in Europe and aim to reduce their population. The objective of an effective population control of coypu and muskrat is to protect lowlands from flooding, to prevent crop damage and loss of biodiversity. The objective of the project is to serve as a pilot and demonstration project in which ‘best practices’ are tested and new techniques are developed for a more efficient control of muskrat and coypu populations. By involving organisations from Belgium, Germany and the Netherlands, the project also promotes international cooperation and knowledge exchange in the field of muskrat and coypu management.
## Funding
LIFE programme
## Study area description
Belgium, the Netherlands, Germany

**Comment by DimEvil** [comment]
ok for MICA NLBIF
