### ISSUE TITLE
Update dataset descriptions

### ISSUE THREAD

**Issue by peterdesmet** [inbo/mica-occurrences#18]
- [x] http://ipt.nlbif.nl/resource?r=mica-uvw-occurrences

> MICA - Muskrat and coypu occurrences collected by UVW in the Netherlands is an occurrence dataset published by the Research Institute of Nature and Forest (INBO) and the Netherlands Biodiversity Information Facility (NLBIF). It is part of the LIFE project MICA, in which innovative techniques are tested for a more efficient control of muskrat and coypu populations, both invasive species. This dataset contains muskrat and coypu counts. Here it is published as a standardized Darwin Core Archive and includes for each occurrence record an occurrenceID, date, location, the number of recorded individuals, status (present/absent) and scientific name. Issues with the dataset can be reported at https://github.com/inbo/mica-occurrences/issues
> 
> We have released this dataset to the public domain under a Creative Commons Zero waiver. We would appreciate it if you follow the INBO norms for data use (https://www.inbo.be/en/norms-data-use) when using the data. If you have any questions regarding this dataset, don't hesitate to contact us via the contact information provided in the metadata or via opendata@inbo.be.
> 
> The data were collected as part of the MICA project, which received funding from the European Union’s LIFE Environment sub-programme under the grant agreement LIFE18 NAT/NL/001047.

- [x] https://ipt.inbo.be/resource?r=mica-rato-occurrences

> MICA - Muskrat occurrences collected by RATO in East Flanders, Belgium is an occurrence dataset published by the Research Institute of Nature and Forest (INBO). It is part of the LIFE project MICA, in which innovative techniques are tested for a more efficient control of muskrat and coypu populations, both invasive species. This dataset contains muskrat trap captures. Here it is published as a standardized Darwin Core Archive and includes for each occurrence record an occurrenceID, date, location, the number of recorded individuals, status (present/absent) and scientific name. Issues with the dataset can be reported at https://github.com/inbo/mica-occurrences/issues
> 
> We have released this dataset to the public domain under a Creative Commons Zero waiver. We would appreciate it if you follow the INBO norms for data use (https://www.inbo.be/en/norms-data-use) when using the data. If you have any questions regarding this dataset, don't hesitate to contact us via the contact information provided in the metadata or via opendata@inbo.be.
> 
> The data were collected as part of the MICA project, which received funding from the European Union’s LIFE Environment sub-programme under the grant agreement LIFE18 NAT/NL/001047.

- [x] https://ipt.inbo.be/resource?r=mica-legacy-occurrences

> Muskrat captures in Flanders, Belgium is an occurrence dataset published by the Research Institute for Nature and Forest (INBO). It contains information on all officially registered captures of muskrat (Ondatra zibethicus) in and around Flanders, Belgium between 1991 and 2018. These data are provided by different management actors: the Flanders Environment Agency (VMM), Rattenbestrijding Oost-Vlaanderen (RATO vzw), Polders and Wateringen (vvpw), and provincial and municipal trappers, and aggregated and analyzed by the INBO since 1991. Here it is published as a standardized Darwin Core Archive and includes for each occurrence record an occurrenceID, date, location, samplingProtocol (trap) and samplingEffort (number of days or traps), scientific name, and the organization who made the capture. The original dataset contains close to 450.000 occurrences and is available on GitHub, but only presence records (over 103.000) are included in this version, which can be used to track muskrat distribution in Flanders since 1991. Issues with the dataset can be reported at https://github.com/inbo/mica-occurrences/issues
> 
> We have released this dataset to the public domain under a Creative Commons Zero waiver. We would appreciate it if you follow the INBO norms for data use (https://www.inbo.be/en/norms-data-use) when using the data. If you have any questions regarding this dataset, don't hesitate to contact us via the contact information provided in the metadata or via opendata@inbo.be.
> 
> This dataset was published for the MICA project, which received funding from the European Union’s LIFE Environment sub-programme under the grant agreement LIFE18 NAT/NL/001047.

**Comment by DimEvil** [comment]
ok for MICA NLBIF
