### ISSUE TITLE
mica-agouti eventRemarks

### ISSUE THREAD

**Issue by DimEvil** [inbo/mica-occurrences#4]
In dwc_occurrence we have in eventRemarks values like:  'batterijen vervangen | tags: rechteroever' and 'begin 19/06 tot 16/07 7228 foto's | tags: linkeroever'

Do we want this in the published dataset or can we just remove this column

**Comment by jimcasaer** [comment]
I would suggest to remove -- @EmmaCartuyvels1 do you agree ?

**Comment by DimEvil** [comment]
> I would suggest to remove -- @EmmaCartuyvels1 do you agree ?

no problem

**Comment by EmmaCartuyvels1** [comment]
> I would suggest to remove -- @EmmaCartuyvels1 do you agree ?

I agree!

**Comment by DimEvil** [comment]
consider it done!
