### ISSUE TITLE
individualCount, sex and occurrenceRemarks doesn't always add up

### ISSUE THREAD

**Issue by DimEvil** [inbo/mica-occurrences#5]
The numbers doesn't always count up. For example I have
occurrenceRemarks: Moeder en 2 kindjes  individualCount: 3 **&**  occurrenceRemarks: Moeder en 2 kindjes  individualCount: 1

What to do here?

I would suggest to skip occurrenceRemarks, (as this is only given for like 250 records) and it also contains stuff like 'mooie foto'.

But also important information is sometimes to be found there:  'staart bever volgens Kristof' and discussion on the validation of the record. We have 'Canis familiaris' when the scientificName is 'Canis lupus'.  We cant' publish records of wolves when we are not absolutely sure. And Canis familiaris is not a valid name for Agouti it seems..

**Comment by peterdesmet** [comment]
Can you give the occurrence ID(s) for the "Moeder en 2 kindjes" remark?

Agree that occurrenceRemarks can probably be skipped.

Can you create a separate issue for the Canis lupus issue?

**Comment by jimcasaer** [comment]
Indeed, drop occurenceRemarks for publication on GBIF - is internal information and not checked

**Comment by DimEvil** [comment]
b6e112f9-c9ec-4b90-9778-d61763dfda6a @peterdesmet   (But there are more examples)

@jim ok to drop, but what if it is contradictory to the scientificName in the dataset?
