### ISSUE TITLE
Mica Agouti location

### ISSUE THREAD

**Issue by DimEvil** [inbo/mica-occurrences#6]
Is there a coordinate uncertainty foreseen for this dataset. I imagine that we do not wan't to publish the exact location of the camera traps. 

which location is given (is this already with an uncertainty?)
What is the coordinateUncertaintyInMeters for this dataset

**Comment by peterdesmet** [comment]
This is for @jimcasaer to decide.

**Comment by jimcasaer** [comment]
There is no known uncertainty,
Camera locations were measured in the field using GPS or pinpointed on the map
Is it common practice to add an uncertainty (say 250 m) on these kind of locations when publishing on GBIF ?

**Comment by DimEvil** [comment]
@jimcasaer  Normally we add 30 meters to a GPS location. But if you wan't 250, this is also possible
We have 5 fractional digits, so we could use only 4 to make the location a little more unclear. 

Normally I would keep the highest resolution possible, but as there is a camera hidden there, this might be tricky. (Your call)

**Comment by jimcasaer** [comment]
@EmmaCartuyvels1 I suggest to publish only up to 3 fractional digits -- the location is still accurate enough to be useful without risk of revealing/finding the camera 

@DimEvil : can we add in the metadata that the exact locations can be asked to the authors for scientific research ?

**Comment by EmmaCartuyvels1** [comment]
> @EmmaCartuyvels1 I suggest to publish only up to 3 fractional digits -- the location is still accurate enough to be useful without risk of revealing/finding the camera
> 
> @DimEvil : can we add in the metadata that the exact locations can be asked to the authors for scientific research ?

Good suggestion @jimcasaer !

**Comment by DimEvil** [comment]
@jimcasaer  We can add everything we want in the metadata, so we will do that!! I will adapt the coordinateUncertaintyInMeters to the 3 fractional digits idea. (would be like 250 meters..I guess)

**Comment by peterdesmet** [comment]
Reopened, as original script still has 4 decimals. Should we guess a coordinateUncertaintyInMeters or just use coordinatePrecision?

**Comment by peterdesmet** [comment]
If we want to keep using `coordinateUncertaintyInMeters` note that the precision is than 111m or less: https://wiki.openstreetmap.org/wiki/Precision_of_coordinates#Precision_of_latitudes I would opt for `111`

**Comment by peterdesmet** [comment]
Set to 3 decimals and 111m in Rmd
