### ISSUE TITLE
Canis lupus vs Canis familiaris

### ISSUE THREAD

**Issue by DimEvil** [inbo/mica-occurrences#8]
We have 'Canis familiaris' in occurrenceREmarks when the scientificName is 'Canis lupus'.  (dab4021f-a26d-4127-9559-bc6a6833d870)

We cant' publish records of wolves when we are not absolutely sure. And Canis familiaris is not a valid name for Agouti it seems..

Some occurrenceRemarks annotate the scientificName like in the case of the wolf, but also Rattus norvegicus in scientificName and Gedeeltelijk zichtbaar. Harig => Zeker soort rat  in occurrenceRemarks  (3cd7759c-6c1d-414f-a90a-2c161a5e2aeb)

**Comment by jimcasaer** [comment]
@DimEvil is domesticated not 'vinked' for the canis lupus ?

**Comment by DimEvil** [comment]
@jimcasaer  As far as I can see in the dwc_occurrence data, there is no such information

When we would provide a 'tag' *domestic*, I'm not in favour to publish it that way as probably only few will notice

**Comment by peterdesmet** [comment]
The domestic flag still needs to be added to the generic Darwin Core export (see discussion at https://github.com/tdwg/dwc-for-biologging/issues/37). But even if we have that flag, I would not necessarily publish `Canis lupus` records, but transform these into `Canis familiaris`.

**Comment by DimEvil** [comment]
ok, but what do I do now, as we are planning to publish this data. (Leave the wolves out of it for the moment?)

**Comment by peterdesmet** [comment]
I would change all `Canis lupus` to `Canis familiaris`, as I don't think there are wolves in this dataset. @jimcasaer?

**Comment by DimEvil** [comment]
@peterdesmet @jimcasaer   is there any need to publish domestic animals? In other words... Is this data important for Agouti?
We could for the next update only publish the non domestic data?

**Comment by peterdesmet** [comment]
> is there any need to publish domestic animals

Interesting question, they would be included in an Agouti export, but I could exclude them from Darwin Core. That would solve a whole bunch of issue. @jimcasaer?

**Comment by peterdesmet** [comment]
We currently still have:

14	Canis lupus	species	gray wolf	1
15	Canis lupus familiaris	subspecies	dog	21

**Comment by peterdesmet** [comment]
Fixed in Rmd now
