### ISSUE TITLE
identifiedBy

### ISSUE THREAD

**Issue by DimEvil** [inbo/mica-occurrences#9]
Do we keep the names of the identifiers (identifiedBy)? Of do we anonymise them?

**Comment by jimcasaer** [comment]
when anonymised we can still see is they were identified by the same person ? @DimEvil

**Comment by DimEvil** [comment]
@jim yes, the same persons always gets the same code

**Comment by peterdesmet** [comment]
Agouti users can indicate in their profile if they want to be anonymous in exports. Then they get a code. So no need to anonymize further for Darwin Core (as it is already the case).

**Comment by jimcasaer** [comment]
?? where do we indicate this ??

**Comment by peterdesmet** [comment]
This will be available in version 3.7

**Comment by DimEvil** [comment]
So what do I do now? Publish with names as is? I just need an answer for what I need to do...

**Comment by peterdesmet** [comment]
Yes, publish names as is.

**Comment by DimEvil** [comment]
yeah! we close this issue!
